# ---- Base Node ----
FROM node:22-alpine3.20 AS base

WORKDIR /app

# ---- Dependencies ----
FROM base AS dependencies

COPY package.json ./
COPY package-lock.json ./

RUN npm install

# ---- Build ----
FROM dependencies AS build

COPY . .

RUN npm run build


# ---- Production ----
FROM node:22-alpine3.20 AS production

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

ENV NODE_ENV=production

EXPOSE 5000

CMD ["node", "dist/app.js"]

