services:
  some-mongo:
    image: mongo:8.0.3
    volumes:
      - db_mongo:/data/db
    networks:
      - lemoncode-challenge
  
  topics-api:
    build:
      context: ./backend
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - some-mongo
    networks:
      - lemoncode-challenge
  
  frontend:
    build:
      context: ./frontend
    environment:
      - API_URI=http://topics-api:5000/api/topics
    ports:
      - "8080:3000"
    networks:
      - lemoncode-challenge

volumes:
  db_mongo:
    external: true

networks:
  lemoncode-challenge: