apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: lemoncodersbc/lc-todo-monolith-db:v5-2024
        envFrom:
        - configMapRef:
            name: todo-app-variables
        ports:
          - containerPort: 3000